### ISSUE TITLE
CMake: missing MRA-datatypes is missing target_link_libraries of MRA-components-proto 

### ISSUE THREAD

**Issue by jveijck** [janfeitsma/MRA-prototype#3]
https://github.com/janfeitsma/MRA-prototype/blob/37f4b396dd1116abf7c18948e1c2f304229acc62/CMakeLists.txt#L73

current code:
`target_link_libraries(MRA-components-proto protobuf)`

proposed change
`target_link_libraries(MRA-components-proto MRA-datatypes protobuf)`    
(add **MRA-datatypes**)

After applying the proposed change, link issues for cmake are solved.
(generate enum code can be found)

**Comment by janfeitsma** [comment]
Looks good. Will fix it now. 

(For next time: this fix is so trivial, feel free to make a PR yourself for stuff like this, or even directly push it into `main`, provided I setup the access correctly. 
Then we have less administration overhead and less wondering who is fixing what now. For now this repo is "ours" anyway ;).)
