### ISSUE TITLE
Move repo to https://github.com/RoboCup-MSL

### ISSUE THREAD

**Issue by janfeitsma** [janfeitsma/MRA-prototype#32]
As discussed in MRA community discord meeting 28 september.
Let's end the prototype phase and move this repo to the official MSL project https://github.com/RoboCup-MSL

Constraint: just a move, no significant structure changes for now. First the developer base needs to grow a bit.

Proposal / details of what I am planning to do. Comments welcome.
- [x] choose new name: rename from `MRA-prototype` to `MRA-components` (why not just `MRA`: to signal that the content is mainly about component sharing, also anticipating more MRA-related repos (logging, documents, engine))
- [x] pick a date: around 12 october (best not to have too many open PR's by then!)
- [x] create new repo and push existing content into it
- [x] update README slightly, to drop the "prototype" notes etc
- [x] use some tool (`github-to-jira`?) to migrate the relevant open issues, or do it manually
- [x] verify (are CI/CD pipelines correctly setup, are links still working)
- [x] give green light to developers (just Jurge and me I guess) who already have a local checkout: `git remote set-url origin https://github.com/RoboCup-MSL/MRA-components.git`
- [ ] update references in Falcons repo + gitlab
- [x] mark this repo as obsolete but do not delete it yet

**Comment by janfeitsma** [comment]
I did not push **_all_** existing branches. From current prototype repo, after having updated to the new origin, just push whichever branch we still need.

**Comment by janfeitsma** [comment]
Decided to not migrate all open issues, better to do this manually while reconsidering.

**Comment by janfeitsma** [comment]
Decided to not just yet update Falcons references. For the rest: all done!

**Comment by jveijck** [comment]
robotsports is moved to MRA-components..
This repo is still needed for the issues.
